<script src="<?php echo $this->config->base_url(); ?>assets/js/jquery.js"></script><script src="<?php echo $this->config->base_url(); ?>assets/js/jquery-ui-1.9.2.custom.min.js"></script> <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script><script type="text/javascript">	$(document).ready(function(){				$( "#export" ).click(function() {		var estado = $('#estado').val();			var cidade = $('#cidade').val();			var cnpj = $('#cnpj').val();				$("#estadoExp").val(estado);		$("#cidadeExp").val(cidade);		$("#cnpjExp").val(cnpj);		$("#exportForm").submit();	});				$( "#ano" ).change(function() {		var ano = $('#ano').val();			$.getJSON('<?php echo $this->config->base_url();?>index.php/intimacoes/listarClassificacaoIntimacaoJson/0/'+ano, function (dados){			 if (dados.length > 0){    				  var option = '<option value=0>Selecione</option>';				  $.each(dados, function(i, obj){						if(obj.id_classificacao){							option += '<option value="'+obj.id_classificacao+'">'+obj.desc_classificacao+'</option>';  						}				  })				  $('#id_classificacao').html(option).show();			   }else{				   option = '<option>Não foram encontrados classificações!</option>';				   $('#id_classificacao').html(option).show();			   }    			  		});		});		var estadoI = $('#estado').val();		var anoI = $('#ano').val();			var idClassificacaoBd = $('#idClassificacaoBd').val();		$.getJSON('<?php echo $this->config->base_url();?>index.php/intimacoes/listarClassificacaoIntimacaoJson/0/'+anoI, function (dados){         if (dados.length > 0){                  var option = '<option value=0>Selecione</option>';              $.each(dados, function(i, obj){					if(obj.id_classificacao){						if(idClassificacaoBd == obj.id_classificacao){							option += '<option selected value="'+obj.id_classificacao+'">'+obj.desc_classificacao+'</option>';  						}else{							option += '<option value="'+obj.id_classificacao+'">'+obj.desc_classificacao+'</option>';  						}					}              })              $('#id_classificacao').html(option).show();           }else{			   option = '<option>Não foram encontrados classificações!</option>';			   $('#id_classificacao').html(option).show();           }              	});			    $( "#limpar" ).click(function() {					$("#limpar_filtro").submit();			});	  
});			google.charts.load('current', {'packages':['bar']});      google.charts.setOnLoadCallback(drawChart);      function drawChart() {        var data = google.visualization.arrayToDataTable([          ['Classificação', 'Total Valores Defensáveis', 'Total Valor Principal'],		  <?php			foreach($dados as $key => $emitente){ 					$total_valores_Defensaveis =  $emitente->total_valores_Defensaveis;				$total_valor_principal = $emitente->total_valor_principal;						echo "['$emitente->descricao_tributo_classificacao',$total_valores_Defensaveis,$total_valor_principal],";			}		  ?>												          // ['CREDITO ENERGIA ELETRICA', 1000, 400],          // ['AUTO REGULARIZAÇÃO', 1170, 460],          // ['Documentos fiscais de entrada não escriturados', 660, 1120],          // ['ENVIO DE DOCS FISCAIS', 1030, 540],		  // ['ENVIO DE DOCS FISCAIS', 1030, 540],		  // ['ENVIO DE DOCS FISCAIS', 1030, 540],		  // ['ENVIO DE DOCS FISCAIS', 1030, 540],		  // ['ENVIO DE DOCS FISCAIS', 1030, 540]		           ]);        var options = {          chart: {            title: 'Gráfico por Classificação/Ano com Valores',          },          bars: 'vertical' // Required for Material Bar Charts.        };				var formatter = new google.visualization.NumberFormat({              decimalSymbol: ',',              groupingSymbol: '.',              prefix: 'R$ '        });		// Estou aplicando para as colunas 2 e 3		formatter.format(data, 1);		formatter.format(data, 2);        var chart = new google.charts.Bar(document.getElementById('barchart_material'));        chart.draw(data, google.charts.Bar.convertOptions(options));      }	  
</script>		<div id="wrapper">                <div class="content-wrapper container">                    <div class="row">                        <div class="col-sm-12">                            <div class="page-title">                                <h1>Intima&ccedil;&otilde;es <small>	</small></h1>                                <ol class="breadcrumb">                                                                        <li class="active">Classificação/Ano </li>                                </ol>                            </div>                        </div>                    </div><!-- end .page title-->                    <div class="row">                        <div class="col-md-12">                            <div class="panel panel-card ">                                <!-- Start .panel -->                                <div class="panel-heading">									<br>										<?php									$attributes = array('class' => 'form-horizontal style-form','id' => 'form' );									echo form_open('intimacoes/classificacao_ano', $attributes); 									?>									Ano - Ci&ecirc;ncia									<select name="ano" id="ano" class='procuraImovel'>										<?php										foreach($anos as $row) {											if($row->ano == $ano){												echo "<option value='$row->ano' selected>$row->ano</option>";												}else{												echo "<option value='$row->ano'>$row->ano</option>";											}																					}										?>																			 									</select>										&nbsp;										<input type='hidden' id='idClassificacaoBd' name='idClassificacaoBd' value='<?php echo$idClassificacao?>'>														 									&nbsp;										Classificação									<select class='procuraImovel' name='id_classificacao' id="id_classificacao" required>									<option value=""> Selecione</option>									<?php									foreach($classificacao as $row) {									  echo "<option value='$row->id_classificacao'>$row->id_classificacao</option>";									}									?>									</select>					  								 <button class="btn btn-primary" style='height:28px!important' type="submit">Filtrar</button>								 <p class="btn btn-primary" style='height:28px!important' id='limpar'>Limpar Filtro</p>								 </form>									                                    <div class="panel-actions">
                                        <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
                                        <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>
                                    </div>
                                </div>								<div class="panel-body">								<?php 								if(($grafico == 1) and (count($dados) <> 0) ){?>								<div id="barchart_material" style="width: 1200px; height: 500px;"></div>								<?php }?>								</div>								
                                 <div class="panel-body">
                                    <table  id="basic-datatables" class="table table-bordered" cellspacing="0" width="100%">                                        <thead>                                            <tr>												  <th > Ano</th>												  <th > Classifica&ccedil;&atilde;o </th>												  <th > Total Valores defens&aacute;veis </th>												  <th > Total Valor Principal</th>                                            </tr>
                                        </thead>
                                        <tfoot>                                            <tr>												  <th > Ano</th>												  <th > Classifica&ccedil;&atilde;o </th>												  <th > Total Valores defens&aacute;veis </th>												  <th > Total Valor Principal</th>                                            </tr>		  
                                            </tr>
                                        </tfoot>
                                        <tbody>
										<?php 	foreach($dados as $key => $emitente){ 													$emitente->total_valores_Defensaveis =  number_format($emitente->total_valores_Defensaveis, 2, ',', '.');												$emitente->total_valor_principal = number_format($emitente->total_valor_principal, 2, ',', '.');																						?>
												<tr>												<td ><?php echo $emitente->ano; ?></td>																								<td ><?php echo $emitente->descricao_tributo_classificacao; ?></td>																								<td ><?php echo $emitente->total_valores_Defensaveis; ?></td>																								<td ><?php echo $emitente->total_valor_principal; ?></td>																								</tr>
										 <?php }//fim foreach  ?>
                                        </tbody>
                                    </table>
                                </div>								
                            </div><!-- End .panel -->  
                        </div><!--end .col-->
                    </div><!--end .row-->                </div> 
            </div>