<script src="<?php echo $this->config->base_url(); ?>assets/js/jquery.js"></script><script src="<?php echo $this->config->base_url(); ?>assets/js/jquery-ui-1.9.2.custom.min.js"></script><script type="text/javascript">     $(document).ready(function(){		$.getJSON('<?php echo $this->config->base_url();?>index.php/captura/listarEstadoComCnpj', function (dados){                        if (dados.length > 0){                  var option = '<option value="">Selecione o estado</option>';              $.each(dados, function(i, obj){				  if(obj.uf == '<?php echo$_SESSION['ufCaptura'];?>'){					option += '<option selected value="'+obj.uf+'">'+obj.uf+'</option>';  				  }else{					option += '<option value="'+obj.uf+'">'+obj.uf+'</option>';  				  }              })              $('#estado').html(option).show();           }else{               Reset();			   option = '<option>Não foram encontrados estados!</option>';			   $('#estado').html(option).show();           }        });					$.getJSON('<?php echo $this->config->base_url();?>index.php/captura/listarCnpj?estado=0', function (dados){                        if (dados.length > 0){                  var option = '<option value="">Selecione o cnpj</option>';              $.each(dados, function(i, obj){				  if(obj.cnpj == '<?php echo$_SESSION['cnpjCaptura'];?>'){					option += '<option selected value="'+obj.cnpj+'">'+obj.cnpj+'</option>';  				  }else{					option += '<option value="'+obj.cnpj+'">'+obj.cnpj+'</option>';  				  }              })              $('#cnpj').html(option).show();           }else{               Reset();			   option = '<option>Não foram encontrados estados!</option>';			   $('#cnpj').html(option).show();           }        });				$( "#estado" ).change(function() {			var estado = $('#estado').val();				$.getJSON('<?php echo $this->config->base_url();?>index.php/captura/listarCnpj?estado='+estado, function (dados){								 			   if (dados.length > 0){    				  var option = '<option value="">Selecione o estado</option>';				  $.each(dados, function(i, obj){					  option += '<option value="'+obj.cnpj+'">'+obj.cnpj+'</option>';				  })				  $('#cnpj').html(option).show();			   }else{				    option = '<option value="0">N&atilde;o foi encontrado registro!</option>';				   $('#cnpj').html(option).show();			   }			})		});
				});    </script>           
<div id="wrapper">                <div class="content-wrapper container">                    <div class="row">                        <div class="col-sm-12">                            <div class="page-title">                                <h1>Cadastrar Captura<small></small></h1>                                <ol class="breadcrumb">                                    <li><a href="<?php echo $this->config->base_url();?>index.php/captura/listar"><i class="fa fa-home"></i>Listar Captura</a></li>                                    <li class="active">Cadastrar Captura</li>                                </ol>                            </div>                        </div>                    </div><!-- end .page title-->                    <div class="row">                                               <div class="col-md-12">                            <div class="panel panel-card margin-b-30">                                <!-- Start .panel -->                                <div class="panel-heading">                                    <h4 class="panel-title"> Informa&ccedil;&otilde;es da Captura</h4>                                    <div class="panel-actions">                                        <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>                                        <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>                                    </div>                                </div>								<?php								$attributes = array('class' => 'form-horizontal style-form','id' => 'form' ,'enctype' => 'multipart/form-data');								echo form_open('captura/cadastrar_captura', $attributes); 								?>                                <div class="panel-body">                                 <form class="form-horizontal">                                <div class="form-group" >																			<label class="col-lg-2 control-label">Escolha o Estado (*)</label>                                    <div class="col-lg-4">									<select name="estado" tabindex="1" id="estado"  class='form-control' required=""></select>										</div>																		                                </div>								<div class="form-group" id='cnpj_div'>											<label class="col-lg-2 control-label">Escolha o CNPJ (*) </label>                                    <div class="col-lg-4">										<select name="cnpj" tabindex="2" id="cnpj" class='form-control' required="">										<option value=''> Selecione o Cnpj</option>																			</select>										</div>									                                </div>
																																<div class="form-group">									<label class="col-lg-2 control-label">Upload (*) </label>									<div class="col-lg-4">																				<span class="btn btn-success fileinput-button">										<i class="glyphicon glyphicon-plus"></i>										<span>Upload </span>										<input id="fileupload" type="file" name="userfile[]"  >										</span>                                    </div>										                                </div>
								<div class="hr-line-dashed"></div>
                                <div class="form-group">
                                    <div class="col-sm-4 col-sm-offset-2">
										<button class="btn btn-white" type="submit">Cancelar</button>										<button class="btn btn-primary" type="submit">Salvar/Enviar</button>
                                    </div>
                                </div>
                            </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div> 
            </div>
